### ISSUE TITLE
Harmonize and define SOC role names

### ISSUE THREAD

**Issue by zanerock** [Liquid-Labs/policy-core#24]
## Overview

We need to update our 'roles' document to match with the SOC controls (or vice-a-versa).

## Deliverables

* [x] Update [`roles.json`](https://github.com/Liquid-Labs/policy-core/blob/master/policy/roles.json) with the 'Change Control Board' and other roles gathered from SOC 2 sections 1 & 2 and/or update [`soc-2-type-i.json`](https://github.com/Liquid-Labs/policy-soc2-data/blob/master/soc-2-type-i.compliance.json) to match role names. Include any definition from the SOC controls in the role description. Feel free to change names for clarity or if you find an already defined role under a different name in the `roles.json` document. The SOC 2 names are not required, just that a designated something perform such and such functions.

## Notes

* The [`roles.json`](https://github.com/Liquid-Labs/policy-core/blob/master/policy/roles.json) doc defines the various roles recognized by the policy and which can be assigned to one or more individuals. Roles may be 'singular' or multiple. A 'titular' role would be something that shows up on the org chart. A 'designated' role is something done in addition to the main, org chart functions. For instance the 'Change Control Board' role would be a 'designated' role.

**Comment by killerpeach** [comment]
Below is a list of roles that are referred to in the SOC2 template that are not in roles.json. I added a role column to the [spreadsheet](https://drive.google.com/file/d/1qBMM0AOVhBKLy1J3hc6mPuRnRVT_xkKz/view?usp=sharing).

Next step: develop job descriptions + add to roles.json

Titular roles
- Chief Security Officer


Designated roles
- Client serving
- IT personnel
- Engineering
- Management (unless the policy is referring to SMT, _SOC 1.14, 1.17, 2.1, 2.1 alt_)
- CCB member
- System owners
- Quality Assurance (assign designated role to multiple titular roles)
- Non-developer IT personnel (_SOC 2.8, 2.9_)

**Comment by zanerock** [comment]
Changes made in #25/#26. I reworked the SOC language a bit. Overall simplified things and made clearer to whom the control applied and/or was referring.
